### ISSUE TITLE
cant run like service and broke db after stop few times

### ISSUE THREAD

**Issue by iammelea** [cosmosdevs/stargate#46]
I can run and sync a node with screen, for example, node sync ok when trying to run like service or with one node manager, no works, this is the error
https://paste.ubuntu.com/p/xFDWbVxBc7/

then after check that cant start like service, try to start again with screen and get this error after stop and start more 5 times broke.

https://paste.ubuntu.com/p/tQh2YCYsYK/

I guess have to sync the node again, backup db first and then test things

**Comment by iammelea** [comment]
after unsafe-reset and start with pruning nothing can start like service , now is sync

**Comment by slither05** [comment]
Hey did you resolve the problem ? 🙂

**Comment by taariq** [comment]
@iammelea closing as resolved. Please re-open if not the case on Stargate-3
