### ISSUE TITLE
Mistake on steps

### ISSUE THREAD

**Issue by wimel** [cosmosdevs/stargate#55]
On the [steps](https://github.com/cosmosdevs/stargate#testnet) to compile appears:
```
git checkout https://github.com/cosmos/gaia
git checkout stargate-2
make build
```
but I think the correct is:
```
git clone https://github.com/cosmos/gaia
git checkout stargate-2
make build
```
Also I think it's useful two things:
- Add the `sha256sum` of the [genesis](https://github.com/cosmosdevs/stargate/blob/master/genesis.json)  _(or another check)_

`578e511fa57aae4289171c1a7e8d8b166197595fe70749ee908040db2553f226`

- And clarify that the executable can found on:

`/gaia/build/`

**Comment by taariq** [comment]
Thanks @wimel. Will update.

**Comment by taariq** [comment]
Updated with suggested changes.

**Comment by wimel** [comment]
> Updated with suggested changes.

Thanks @taariq !!
