### ISSUE TITLE
Testing the gov module

### ISSUE THREAD

**Issue by wimel** [cosmosdevs/stargate#64]
Doing some tests to see the `gov` module options, when using the `./gaia/build/gaiad tx gov submit-proposal --help` command provides quite a lot of information, but there is a new command _(`cancel-software-upgrade`)_ that I think is not well explained, this is the output:
```sh
Available Commands:
  cancel-software-upgrade Submit a software upgrade proposal
  community-pool-spend    Submit a community pool spend proposal
  param-change            Submit a parameter change proposal
  software-upgrade        Submit a software upgrade proposal
```

It is possible that the explanation for `cancel-software-upgrade` will be `Cancel previous software upgrade proposal`?

- Steps to reproduce:
```sh
git clone https://github.com/cosmos/gaia
git checkout stargate-3
make build
./gaia/build/gaiad tx gov submit-proposal --help
```

- Version:
```sh
name: gaia
server_name: gaiad
version: stargate-3
commit: 5f28583b510a86fac671e4590d0863d56989735d
build_tags: netgo,ledger
```

- Go version:
`go version go1.14.2 linux/amd64`

**Comment by taariq** [comment]
Thank you @wimel. Taking a look with @zmanian

**Comment by wimel** [comment]
@zmanian Can I help in any way? 
I don't know where the exact route is, but if you tell me where it is I can modify it myself and make a PR with the solution, so if I find any more mistakes I can make the modification and the subsequent PR directly. Thanks!

**Comment by zmanian** [comment]
Just make a PR that changes this line
https://github.com/cosmos/cosmos-sdk/blob/4c762db64efe6dc026071fa1babc9ecef4d24f03/x/upgrade/client/cli/tx.go#L97

**Comment by wimel** [comment]
> Just make a PR that changes this line
> https://github.com/cosmos/cosmos-sdk/blob/4c762db64efe6dc026071fa1babc9ecef4d24f03/x/upgrade/client/cli/tx.go#L97

Ok, done at [PR#7493](https://github.com/cosmos/cosmos-sdk/pull/7493).
Thanks for the help @zmanian.

**Comment by wimel** [comment]
Close the ISSUE, the PR is merge.
