### ISSUE TITLE
when bin/rly testnets request :   gasUsed: 1000: out of gas\n  

### ISSUE THREAD

**Issue by jonathan2004** [cosmosdevs/stargate#65]
bin/rly testnets request chain_1 faucet -u http://127.0.0.1:8000 --home data/relayer
{"error":"transaction failed to execute\nResponse:\n  TxHash: DD779702E8CC32B8547C13C7CC229D2A7E254D24E348F4A4CFAE244D9596512D\n  Code: 11\n  Raw Log: out of gas in location: ReadFlat; gasWanted: 0, gasUsed: 1000: out of gas\n  GasUsed: 1000\n  Codespace: sdk"}

why and how to resolve above question?

**Comment by taariq** [comment]
@jonathan2004 was this resolved?

**Comment by taariq** [comment]
Closing as resolved.
